# Generated by Django 4.1.1 on 2022-11-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='bith_certificate',
            new_name='birth_certificate',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Amount',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='application',
            name='campus',
            field=models.CharField(choices=[('Main Campus', 'Main Campus'), ('Kisumu Town Campus', 'Kisumu Town Campus'), ('Town Campus CBD', 'Town Campus CBD'), ('Marsabit Town Campus', 'Marsabit Town Campus')], max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cohort',
            field=models.CharField(choices=[('January Cohort', 'January Cohort'), ('May Cohort', 'May Cohort'), ('September Cohort', 'September Cohort')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='id_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Computer  Engineering', 'Computer Engineering'), ('Information Technology Management', 'Information Technology Management'), ('Electronics and Telecommunication Engineering', 'Electronics and Telecommunication Engineering'), ('Electronics Engineering', 'Electronics Engineering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_no',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100)),
                ('disability', models.TextField(choices=[('YES', 'YES'), ('NO', 'NO')])),
                ('marita_status', models.TextField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Engaged', 'Engaged'), ('Complicated', 'Complicated'), ('Separated', 'Separated')])),
                ('guardian', models.CharField(max_length=60)),
                ('guardian_number', models.IntegerField(max_length=10)),
                ('guardian_relationship', models.CharField(max_length=10, null=True)),
                ('guardian_region', models.CharField(max_length=10)),
                ('emergency_contact', models.IntegerField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
