# Generated by Django 4.1.1 on 2023-03-02 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_rename_bith_certificate_application_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
